version: '2.4'

services:  
  hasura:
    # image: hasura/graphql-engine:v1.3.3
    image: hasura/graphql-engine:latest.cli-migrations-v2
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    container_name: jwt-hasura
    restart: always
    depends_on:
      - 'postgres'
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'anonymous'
      HASURA_GRAPHQL_DATABASE_URL: 'postgres://postgres:password@postgres:5432/postgres'
      HASURA_GRAPHQL_ADMIN_SECRET: 'password'
      HASURA_GRAPHQL_JWT_SECRET: '{ "type": "HS256", "key": "<32 Character Secret>" }'

  postgres:
    build: ./postgres
    container_name: jwt-pg
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'password'